-- Data Insertion into the Adventure Elements Table

-- Phase 1
INSERT INTO adventure_elements (phase, table_name, table_id, description) VALUES
(1, 'General Type of Scenario', 1, 'Investigation (2)'),
(1, 'General Type of Scenario', 2, 'Survival (3)'),
(1, 'General Type of Scenario', 3, 'Exploration (4)'),
(1, 'General Type of Scenario', 4, 'Assault (5)'),
(1, 'General Type of Scenario', 5, 'Trade (6)'),
(1, 'General Type of Scenario', 6, 'Sacrifice (7)');

-- Phase 2
INSERT INTO adventure_elements (phase, table_name, table_id, description) VALUES
(2, 'Type of Investigation', 1, 'Where are they (4)'),
(2, 'Type of Investigation', 2, 'What happened (8)'),
(2, 'Type of Investigation', 3, 'Where is it (9)'),
(2, 'Type of Investigation', 4, 'What is this (10)'),
(2, 'Type of Investigation', 5, 'How do we stop it (11)'),
(2, 'Type of Investigation', 6, 'Who did this (12)'),
(2, 'Type of Survival', 1, 'Get away from it (11)'),
(2, 'Type of Survival', 2, 'Trapped (13)'),
(2, 'Type of Survival', 3, 'Creeping doom (14)'),
(2, 'Type of Survival', 4, 'Natural disaster (15)'),
(2, 'Type of Survival', 5, 'Hordes of the things (16)'),
(2, 'Type of Survival', 6, 'Assassin (20)'),
(2, 'Type of Exploration', 1, 'Alien structure (17)'),
(2, 'Type of Exploration', 2, 'Abandoned structure (18)'),
(2, 'Type of Exploration', 3, 'Natural phenomena (19)'),
(2, 'Type of Exploration', 4, 'Space (21)'),
(2, 'Type of Exploration', 5, 'Mental (22)'),
(2, 'Type of Exploration', 6, 'Urban (23)'),
(2, 'Type of Assault', 1, 'Stronghold (24)'),
(2, 'Type of Assault', 2, 'Murder (25)'),
(2, 'Type of Assault', 3, 'Uprising (26)'),
(2, 'Type of Assault', 4, 'Kidnap (27)'),
(2, 'Type of Assault', 5, 'War (28)'),
(2, 'Type of Assault', 6, 'Technological (29)'),
(2, 'Type of Trade', 1, 'Small expensive item (30)'),
(2, 'Type of Trade', 2, 'Rare item (31)'),
(2, 'Type of Trade', 3, 'Cargo (32)'),
(2, 'Type of Trade', 4, 'Technology (33)'),
(2, 'Type of Trade', 5, 'Prisoners (34)'),
(2, 'Type of Trade', 6, 'Star ships (35)'),
(2, 'Type of Sacrifice', 1, 'Money (36)'),
(2, 'Type of Sacrifice', 2, 'Livelihood (37)'),
(2, 'Type of Sacrifice', 3, 'Yourself (38)'),
(2, 'Type of Sacrifice', 4, 'An entire people (39)'),
(2, 'Type of Sacrifice', 5, 'Your hopes and dreams (40)'),
(2, 'Type of Sacrifice', 6, 'Time (41)');

-- Phase 3
INSERT INTO adventure_elements (phase, table_name, table_id, description) VALUES
(3, 'What happened', 1, 'Missing person (12)'),
(3, 'What happened', 2, 'A thing appeared (21)'),
(3, 'What happened', 3, 'Missing items (9)'),
(3, 'What happened', 4, 'Murder (12)'),
(3, 'What happened', 5, 'It was moved (42)'),
(3, 'What happened', 6, 'Strange behaviour (22)'),
(3, 'MacGuffin', 1, 'Star ship (35)'),
(3, 'MacGuffin', 2, 'Bundle of cash (36)'),
(3, 'MacGuffin', 3, 'Technological miracle device (19)'),
(3, 'MacGuffin', 4, 'Jewels (36)'),
(3, 'MacGuffin', 5, 'Weapon (11)'),
(3, 'MacGuffin', 6, 'Secret (18)'),
(3, 'Weird item', 1, 'Alien artefact (42)'),
(3, 'Weird item', 2, 'New mineral (35)'),
(3, 'Weird item', 3, 'Sixth sense (20)'),
(3, 'Weird item', 4, 'Psionic item (17)'),
(3, 'Weird item', 5, 'Map (18)'),
(3, 'Weird item', 6, 'Living substance (30)'),
(3, 'Threat', 1, 'Solar event (18)'),
(3, 'Threat', 2, 'Failing crops (7)'),
(3, 'Threat', 3, 'Infestation (28)'),
(3, 'Threat', 4, 'Illness (22)'),
(3, 'Threat', 5, 'Invasion (21)'),
(3, 'Threat', 6, 'Political (19)'),
(3, 'Who', 1, 'Relative (25)'),
(3, 'Who', 2, 'Mysterious stranger (20)'),
(3, 'Who', 3, 'Powerful politician (26)'),
(3, 'Who', 4, 'Lifelong enemy (27)'),
(3, 'Who', 5, 'Insurgent (26)'),
(3, 'Who', 6, 'Alien emissary (42)'),
(3, 'Trap', 1, 'Snipers all around (26)'),
(3, 'Trap', 2, 'Rising water (26)'),
(3, 'Trap', 3, 'Social ties (27)'),
(3, 'Trap', 4, 'Locked exits (40)'),
(3, 'Trap', 5, 'Poisonous atmosphere (44)'),
(3, 'Trap', 6, 'Mental confusion (20)'),
(3, 'Creeping doom', 1, 'Dying sun (12)'),
(3, 'Creeping doom', 2, 'Infestation (16)'),
(3, 'Creeping doom', 3, 'Alien animals (31)'),
(3, 'Creeping doom', 4, 'Asteroid swarm (26)'),
(3, 'Creeping doom', 5, 'Poison air (35)'),
(3, 'Creeping doom', 6, 'Radiation (20)');

-- Additional Data: Natural Disasters, Hordes, Structures, etc.
INSERT INTO adventure_elements (phase, table_name, table_id, description) VALUES
(3, 'Natural disaster', 1, 'Black hole (32)'),
(3, 'Natural disaster', 2, 'Super nova (3)'),
(3, 'Natural disaster', 3, 'Storm (19)'),
(3, 'Natural disaster', 4, 'Drought (36)'),
(3, 'Natural disaster', 5, 'Collapse (21)'),
(3, 'Natural disaster', 6, 'Meteor (19)'),
(3, 'Hordes of the things', 1, 'Intelligent aliens (20)'),
(3, 'Hordes of the things', 2, 'Alien animals (42)'),
(3, 'Hordes of the things', 3, 'Insects (11)'),
(3, 'Hordes of the things', 4, 'Micro-bots (5)'),
(3, 'Hordes of the things', 5, 'Fighter craft (27)'),
(3, 'Hordes of the things', 6, 'Mobile fungi (28)'),
(3, 'Alien Structure', 1, 'Hive ship (28)'),
(3, 'Alien Structure', 2, 'Abandoned station (44)'),
(3, 'Alien Structure', 3, 'Religious temple (29)'),
(3, 'Alien Structure', 4, 'Asteroid colony (44)'),
(3, 'Alien Structure', 5, 'Dead city (31)'),
(3, 'Alien Structure', 6, 'Military base (11)'),
(3, 'Abandoned structure', 1, 'Power station (35)'),
(3, 'Abandoned structure', 2, 'Floating framework (24)'),
(3, 'Abandoned structure', 3, 'Inverted pyramid (34)'),
(3, 'Abandoned structure', 4, 'Subterranean cavern (23)'),
(3, 'Abandoned structure', 5, 'Arena (42)'),
(3, 'Abandoned structure', 6, 'City (29)'),

-- Urban, Stronghold, Murder, Uprising, etc.
INSERT INTO adventure_elements (phase, table_name, table_id, description) VALUES
(3, 'Urban', 1, 'Old factory complex (16)'),
(3, 'Urban', 2, 'The sewer system (12)'),
(3, 'Urban', 3, 'Abandoned apartment building (44)'),
(3, 'Urban', 4, 'Active atmosphere processor (29)'),
(3, 'Urban', 5, 'Ancient fortress (10)'),
(3, 'Urban', 6, 'Newly discovered alien environment (35)'),
(3, 'Stronghold', 1, 'Bunker complex (21)'),
(3, 'Stronghold', 2, 'Prefabricated fort (32)'),
(3, 'Stronghold', 3, 'Massive ancient tower (15)'),
(3, 'Stronghold', 4, 'Natural cave system (44)'),
(3, 'Stronghold', 5, 'Military camp (32)'),
(3, 'Stronghold', 6, 'Vehicular laager (39)'),
(3, 'Murder', 1, 'Legal execution (18)'),
(3, 'Murder', 2, 'Bloody reprisal (12)'),
(3, 'Murder', 3, 'Back alley mugging gone wrong (37)'),
(3, 'Murder', 4, 'Overdose (40)'),
(3, 'Murder', 5, 'Mass killing (26)'),
(3, 'Murder', 6, 'Starvation (27)'),
(3, 'Uprising', 1, 'Slave revolt (36)'),
(3, 'Uprising', 2, 'Military coup (32)'),
(3, 'Uprising', 3, 'Democratic movement (39)'),
(3, 'Uprising', 4, 'Provincial independence declaration (22)'),
(3, 'Uprising', 5, 'General strike (25)'),
(3, 'Uprising', 6, 'Ethnic aggression (30)'),
(3, 'Kidnap', 1, 'Protagonist (23)'),
(3, 'Kidnap', 2, 'Sibling or parent (43)'),
(3, 'Kidnap', 3, 'Employer (20)'),
(3, 'Kidnap', 4, 'Extended family (22)'),
(3, 'Kidnap', 5, 'Friend / Neighbour (36)'),
(3, 'Kidnap', 6, 'Child (23)'),
(3, 'War', 1, 'Capture equipment (35)'),
(3, 'War', 2, 'Kill leader (41)'),
(3, 'War', 3, 'Hold the line (41)'),
(3, 'War', 4, 'Take that hill (22)'),
(3, 'War', 5, 'Demolish structure (23)'),
(3, 'War', 6, 'Aggressive patrol (41)'),
(3, 'Technological', 1, 'Power out (41)'),
(3, 'Technological', 2, 'Communications block (39)'),
(3, 'Technological', 3, 'Robotic mayhem (42)'),
(3, 'Technological', 4, 'Overload explosion (44)'),
(3, 'Technological', 5, 'Life support failure (24)'),
(3, 'Technological', 6, 'Out of control vehicles (35)');

-- Cargo, Technology, Prisoners, Star Ships, etc.
INSERT INTO adventure_elements (phase, table_name, table_id, description) VALUES
(3, 'Cargo', 1, 'Weapons (37)'),
(3, 'Cargo', 2, 'Rare earth (18)'),
(3, 'Cargo', 3, 'Industrial gems (27)'),
(3, 'Cargo', 4, 'Animals (42)'),
(3, 'Cargo', 5, 'Engine parts ((23))'),
(3, 'Cargo', 6, 'Food (16)'),
(3, 'Technology', 1, 'Ship engines (44)'),
(3, 'Technology', 2, 'Laser crystal (24)'),
(3, 'Technology', 3, 'Guidance system (44)'),
(3, 'Technology', 4, 'Comm''s gear (34)'),
(3, 'Technology', 5, 'Power source (6)'),
(3, 'Technology', 6, 'Computer parts (25)'),
(3, 'Prisoners', 1, 'Prisoners of war (27)'),
(3, 'Prisoners', 2, 'Murderers (25)'),
(3, 'Prisoners', 3, 'Slaves (39)'),
(3, 'Prisoners', 4, 'Indentured workers (22)'),
(3, 'Prisoners', 5, 'Captured aliens (35)'),
(3, 'Prisoners', 6, 'Political rivals (25)'),
(3, 'Star Ships', 1, 'Irradiated hulk (30)'),
(3, 'Star Ships', 2, 'Damaged scout (37)'),
(3, 'Star Ships', 3, 'New Corvette (25)'),
(3, 'Star Ships', 4, 'Alien spy vessel (40)'),
(3, 'Star Ships', 5, 'Demolished trader (43)'),
(3, 'Star Ships', 6, 'Bulk fuel carrier (25)');

-- Final Categories: An Entire People, Hopes and Dreams, Time, Moved, Skills, Failure
INSERT INTO adventure_elements (phase, table_name, table_id, description) VALUES
(3, 'An Entire People', 1, 'An extended family (15)'),
(3, 'An Entire People', 2, 'The whole tribe (26)'),
(3, 'An Entire People', 3, 'The last of the race (28)'),
(3, 'An Entire People', 4, 'The complete colony (4)'),
(3, 'An Entire People', 5, 'The crew (22)'),
(3, 'An Entire People', 6, 'All the witnesses (11)'),
(3, 'Hopes and Dreams', 1, 'Inheritance lost (15)'),
(3, 'Hopes and Dreams', 2, 'Loved one leaves (38)'),
(3, 'Hopes and Dreams', 3, 'Holiday venue destroyed (28)'),
(3, 'Hopes and Dreams', 4, 'Criminal record (39)'),
(3, 'Hopes and Dreams', 5, 'Poor health (39)'),
(3, 'Hopes and Dreams', 6, 'Irrational fear (31)'),
(3, 'Time', 1, 'The next week (30)'),
(3, 'Time', 2, 'One year (25)'),
(3, 'Time', 3, 'A decade (34)'),
(3, 'Time', 4, 'Six months (30)'),
(3, 'Time', 5, 'Every Monday (27)'),
(3, 'Time', 6, 'Retirement (31)'),
(3, 'Moved', 1, 'Hidden next door (22)'),
(3, 'Moved', 2, 'On the star ship (29)'),
(3, 'Moved', 3, 'The next town (22)'),
(3, 'Moved', 4, 'On another planet (32)'),
(3, 'Moved', 5, 'Across the world (37)'),
(3, 'Moved', 6, 'The next subsector (33)'),
(3, 'Skills', 1, 'Computer (22)'),
(3, 'Skills', 2, 'Melee (20)'),
(3, 'Skills', 3, 'Firearm (28)'),
(3, 'Skills', 4, 'Piloting (21)'),
(3, 'Skills', 5, 'Navigation (19)'),
(3, 'Skills', 6, 'Social (7)'),
(3, 'Failure', 1, 'Accident (40)'),
(3, 'Failure', 2, 'Sabotage (35)'),
(3, 'Failure', 3, 'Wear and tear (33)'),
(3, 'Failure', 4, 'Faulty material (36)'),
(3, 'Failure', 5, 'Operator error (13)'),
(3, 'Failure', 6, 'Corrosion (33)');
