[Themes]
light = Noto Sans
dark = Noto Sans
lcars = Ubuntu Sans
matrix = DejaVu Sans Mono

[Defaults]
size = 10
weight = Normal

[Alternatives]
light = Liberation Sans, DejaVu Sans
dark = Liberation Sans, DejaVu Sans
lcars = Noto Sans, Liberation Sans
matrix = Liberation Mono, Courier New
